update test to run snakemake and compare outputs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,6 +20,15 @@ jobs:
           conda activate ./env
           set -e
           time snakemake -pr -j4 --configfile config/test-config.yaml --resources wget_limit=2
+          diff mappings/test/fasta1_to_fasta2/mappings_fasta1_to_fasta2.tsv tests/expected_results/fasta1_to_fasta2/mappings_fasta1_to_fasta2.tsv \
+            > tests/expected_results/diff.log 2>> tests/expected_results/diff.log
+          if [ -s tests/expected_results/diff.log ]
+          then
+            echo "FAILED, see tests/expected_results/diff.log"
+            exit 1
+          else
+            echo "PASSED"
+          fi
 
     - name: run pytest
       run: |
